# medical_whitelist.py - Clinical terms that should NOT be de-identified
# These are medical terms that pattern-match as names (Title Case two-word phrases)
# but are actually clinical terminology that must be preserved.
#
# Usage: from medical_whitelist import MEDICAL_WHITELIST
#        if detected_text in MEDICAL_WHITELIST:
#            skip_replacement()
#
# Last Updated: December 8, 2025
# Maintainer: Gary Riggs, MD | RIGGSMED LLC

MEDICAL_WHITELIST = {
    # === LAB VALUES & CHEMISTRY ===
    "Anion Gap",
    "Base Excess",
    "Base Deficit",
    "Blood Gas",
    "Blood Gases",
    "Carbon Dioxide",
    "Direct Bilirubin",
    "Indirect Bilirubin",
    "Total Bilirubin",
    "Conjugated Bilirubin",
    "Unconjugated Bilirubin",
    "Blood Urea",
    "Urea Nitrogen",
    "Lactic Acid",
    "Uric Acid",
    "Folic Acid",
    "Ascorbic Acid",
    "Fatty Acids",
    "Amino Acids",
    "Nucleic Acids",
    "Bile Acids",
    "Vanillylmandelic Acid",
    "Homovanillic Acid",
    "Delta Aminolevulinic Acid",
    
    # === HEMATOLOGY ===
    "White Blood",
    "Red Blood",
    "White Count",
    "Red Count",
    "Platelet Count",
    "Blood Count",
    "Mean Corpuscular",
    "Mean Platelet",
    "Red Cell",
    "White Cell",
    "Packed Cell",
    "Reticulocyte Count",
    "Absolute Neutrophil",
    "Absolute Lymphocyte",
    "Absolute Monocyte",
    "Absolute Eosinophil",
    "Absolute Basophil",
    "Band Neutrophils",
    "Segmented Neutrophils",
    "Atypical Lymphocytes",
    "Nucleated Red",
    "Immature Granulocytes",
    "Immature Platelet",
    
    # === COAGULATION ===
    "Partial Thromboplastin",
    "Prothrombin Time",
    "Bleeding Time",
    "Clotting Time",
    "Thrombin Time",
    "Fibrin Degradation",
    "Fibrin Split",
    "Clot Retraction",
    
    # === CARDIAC MARKERS ===
    "Brain Natriuretic",
    "Troponin Level",
    "Cardiac Enzymes",
    "Creatine Kinase",
    "Lactate Dehydrogenase",
    "Myocardial Infarction",
    
    # === RENAL FUNCTION ===
    "Glomerular Filtration",
    "Creatinine Clearance",
    "Urine Output",
    "Urine Osmolality",
    "Serum Osmolality",
    "Fractional Excretion",
    "Tubular Reabsorption",
    
    # === LIVER FUNCTION ===
    "Alkaline Phosphatase",
    "Gamma Glutamyl",
    "Alanine Aminotransferase",
    "Aspartate Aminotransferase",
    "Liver Function",
    "Hepatic Function",
    "Hepatic Panel",
    "Liver Panel",
    "Liver Enzymes",
    
    # === THYROID ===
    "Thyroid Stimulating",
    "Free Thyroxine",
    "Total Thyroxine",
    "Free Triiodothyronine",
    "Thyroid Peroxidase",
    "Thyroid Function",
    "Thyroid Panel",
    "Thyroglobulin Antibodies",
    
    # === LIPID PANEL ===
    "Total Cholesterol",
    "Triglyceride Level",
    "Lipid Panel",
    "Lipid Profile",
    "Lipoprotein Panel",
    "Apolipoprotein Panel",
    
    # === URINALYSIS ===
    "Urine Culture",
    "Urine Protein",
    "Urine Glucose",
    "Urine Ketones",
    "Urine Bilirubin",
    "Urine Urobilinogen",
    "Urine Specific",
    "Specific Gravity",
    "Urine Sediment",
    "Urine Microscopy",
    "Urine Analysis",
    "Clean Catch",
    "Midstream Urine",
    
    # === MICROBIOLOGY ===
    "Blood Culture",
    "Wound Culture",
    "Sputum Culture",
    "Throat Culture",
    "Stool Culture",
    "Cerebrospinal Fluid",
    "Gram Stain",
    "Acid Fast",
    "Colony Count",
    "Sensitivity Testing",
    "Minimum Inhibitory",
    "Bacterial Culture",
    "Fungal Culture",
    "Viral Culture",
    
    # === IMAGING TERMS ===
    "Chest Xray",
    "Chest Film",
    "Portable Chest",
    "Lateral Decubitus",
    "Computed Tomography",
    "Magnetic Resonance",
    "Nuclear Medicine",
    "Positron Emission",
    "Bone Scan",
    "Gallium Scan",
    "Ventilation Perfusion",
    "Contrast Enhanced",
    "Non Contrast",
    "With Contrast",
    "Without Contrast",
    
    # === VITAL SIGNS ===
    "Blood Pressure",
    "Heart Rate",
    "Pulse Rate",
    "Respiratory Rate",
    "Oxygen Saturation",
    "Pulse Oximetry",
    "Temperature Oral",
    "Temperature Rectal",
    "Temperature Axillary",
    "Temperature Tympanic",
    "Pain Scale",
    "Pain Score",
    "Body Mass",
    "Body Weight",
    "Body Temperature",
    
    # === ANATOMY (commonly misidentified) ===
    "Left Atrium",
    "Right Atrium",
    "Left Ventricle",
    "Right Ventricle",
    "Left Arm",
    "Right Arm",
    "Left Leg",
    "Right Leg",
    "Left Eye",
    "Right Eye",
    "Left Ear",
    "Right Ear",
    "Left Lung",
    "Right Lung",
    "Left Kidney",
    "Right Kidney",
    "Upper Extremity",
    "Lower Extremity",
    "Upper Lobe",
    "Lower Lobe",
    "Middle Lobe",
    "Frontal Lobe",
    "Parietal Lobe",
    "Temporal Lobe",
    "Occipital Lobe",
    "Spinal Cord",
    "Brain Stem",
    "Lymph Node",
    "Lymph Nodes",
    
    # === EPONYMOUS CONDITIONS (named after people but are diagnoses) ===
    "Bells Palsy",
    "Bell Palsy",
    "Cushings Syndrome",
    "Cushing Syndrome",
    "Addisons Disease",
    "Addison Disease",
    "Parkinsons Disease",
    "Parkinson Disease",
    "Alzheimers Disease",
    "Alzheimer Disease",
    "Hodgkins Lymphoma",
    "Hodgkin Lymphoma",
    "Non Hodgkins",
    "Non Hodgkin",
    "Graves Disease",
    "Hashimotos Thyroiditis",
    "Hashimoto Thyroiditis",
    "Crohns Disease",
    "Crohn Disease",
    "Barretts Esophagus",
    "Barrett Esophagus",
    "Raynauds Phenomenon",
    "Raynaud Phenomenon",
    "Dupuytrens Contracture",
    "Dupuytren Contracture",
    "Marfan Syndrome",
    "Ehlers Danlos",
    "Down Syndrome",
    "Turner Syndrome",
    "Klinefelter Syndrome",
    "Gilbert Syndrome",
    "Dubin Johnson",
    "Rotor Syndrome",
    "Crigler Najjar",
    "Wilson Disease",
    "Meniere Disease",
    "Menieres Disease",
    "Lou Gehrig",
    "Lou Gehrigs",
    "Guillain Barre",
    "Reye Syndrome",
    "Reyes Syndrome",
    "Stevens Johnson",
    "Kawasaki Disease",
    "Wegener Granulomatosis",
    "Wegeners Granulomatosis",
    "Sjogren Syndrome",
    "Sjogrens Syndrome",
    "Behcet Disease",
    "Behcets Disease",
    "Paget Disease",
    "Pagets Disease",
    "Hirschsprung Disease",
    "Hirschsprungs Disease",
    "Henoch Schonlein",
    "Felty Syndrome",
    "Feltys Syndrome",
    "Still Disease",
    "Stills Disease",
    "Wolff Parkinson",
    "Brugada Syndrome",
    "Osler Weber",
    "Von Willebrand",
    "Christmas Disease",
    "Bernard Soulier",
    "Wiskott Aldrich",
    "Chediak Higashi",
    "Job Syndrome",
    "Jobs Syndrome",
    "DiGeorge Syndrome",
    "Bruton Agammaglobulinemia",
    "Brutons Agammaglobulinemia",
    
    # === CLINICAL SCALES & SCORES ===
    "Glasgow Coma",
    "Apache Score",
    "Apache II",
    "Apache III",
    "Sofa Score",
    "Wells Score",
    "Wells Criteria",
    "Ranson Criteria",
    "Ransons Criteria",
    "Child Pugh",
    "Child Turcotte",
    "Meld Score",
    "Bishop Score",
    "Apgar Score",
    "Braden Scale",
    "Norton Scale",
    "Morse Fall",
    "Karnofsky Score",
    "Karnofsky Performance",
    "Eastern Cooperative",
    "Framingham Risk",
    "Killip Class",
    "Killip Classification",
    "New York Heart",
    
    # === PROCEDURES & TESTS ===
    "Lumbar Puncture",
    "Spinal Tap",
    "Bone Marrow",
    "Fine Needle",
    "Core Biopsy",
    "Open Biopsy",
    "Incision Drainage",
    "Central Line",
    "Arterial Line",
    "Peripheral Line",
    "Foley Catheter",
    "Nasogastric Tube",
    "Endotracheal Tube",
    "Chest Tube",
    "Peg Tube",
    "Tracheostomy Tube",
    
    # === MEDICATION ROUTES ===
    "By Mouth",
    "Per Oral",
    "Per Rectum",
    "Per Vagina",
    "Intravenous Push",
    "Intravenous Drip",
    "Intramuscular Injection",
    "Subcutaneous Injection",
    "Topical Application",
    
    # === CLINICAL STATUS ===
    "Present On",
    "Present Illness",
    "History Of",
    "Chief Complaint",
    "Review Of",
    "Physical Examination",
    "Assessment Plan",
    "Differential Diagnosis",
    "Working Diagnosis",
    "Final Diagnosis",
    "Discharge Diagnosis",
    "Admission Diagnosis",
    "Primary Diagnosis",
    "Secondary Diagnosis",
    "Hospital Course",
    "Clinical Course",
    "Follow Up",
    "Follow-Up",
    
    # === COMMON FALSE POSITIVES FROM LAB SYSTEMS ===
    "Order Status",
    "Order Completed",
    "Order Canceled",
    "Order Cancelled",
    "Order Pending",
    "Specimen Blood",
    "Specimen Urine",
    "Specimen Type",
    "Collection Date",
    "Collection Time",
    "Result Date",
    "Result Time",
    "Reference Range",
    "Critical Value",
    "Critical High",
    "Critical Low",
    "Normal Range",
    "Updated Date",
    "Collected Date",
    "Procedure Name",
    "Component Name",
    "Test Name",
    "Lab Name",
    
    # === EHR TEMPLATE TERMS ===
    "Gen Alert",
    "Gen Appearance",
    "Pertinent Exam",
    "Pertinent Findings",
    "Pertinent Labs",
    "Pertinent History",
    "Pertinent Positives",
    "Pertinent Negatives",
    "Review Systems",
    "Social History",
    "Family History",
    "Past Medical",
    "Past Surgical",
    "Medication List",
    "Allergy List",
    "Problem List",
    "Active Problems",
    "Resolved Problems",
    "Discharge Summary",
    "Progress Note",
    "Admission Note",
    "Consult Note",
    "Operative Note",
    "Procedure Note",
}

# Lowercase version for case-insensitive matching
MEDICAL_WHITELIST_LOWER = {term.lower() for term in MEDICAL_WHITELIST}

def is_medical_term(text: str) -> bool:
    """Check if text is a whitelisted medical term (case-insensitive)."""
    return text.lower() in MEDICAL_WHITELIST_LOWER

def is_medical_term_exact(text: str) -> bool:
    """Check if text is a whitelisted medical term (exact case match)."""
    return text in MEDICAL_WHITELIST
