# whitelist.py - Portuguese terms that should NOT be de-identified
# These are common Portuguese words, abbreviations, and institutional terms
# that could be false positives for name/PII detection.

PII_WHITELIST = {
    # === COMMON PORTUGUESE WORDS THAT LOOK LIKE NAMES ===
    "Esperanca",
    "Esperança",
    "Graca",
    "Graça",
    "Vitoria",
    "Vitória",
    "Gloria",
    "Glória",
    "Conceicao",
    "Conceição",
    "Socorro",
    "Amparo",
    "Piedade",
    "Caridade",
    "Aparecida",
    "Felicidade",
    "Liberdade",
    "Justica",
    "Justiça",
    "Paz",
    "Cruz",
    "Santos",
    "Reis",
    "Flores",

    # === BRAZILIAN GOVERNMENT / INSTITUTION ABBREVIATIONS ===
    "INSS",
    "SUS",
    "FGTS",
    "IBGE",
    "ANVISA",
    "ANATEL",
    "ANAC",
    "DETRAN",
    "SEFAZ",
    "SAMU",
    "PROCON",
    "CREA",
    "OAB",
    "CRM",
    "CRO",
    "COREN",
    "CRF",
    "CRAS",
    "CREAS",
    "SINE",
    "SENAI",
    "SENAC",
    "SEBRAE",
    "INCRA",
    "FUNAI",
    "IBAMA",
    "IPHAN",
    "INEP",
    "CAPES",
    "CNPq",
    "FINEP",
    "BNDES",
    "CEF",
    "BACEN",
    "CVM",
    "SUSEP",
    "PREVIC",
    "TCU",
    "CGU",
    "AGU",
    "MPF",
    "DPU",
    "STF",
    "STJ",
    "TST",
    "TSE",
    "TRF",
    "TRT",
    "TRE",

    # === BRAZILIAN STATE ABBREVIATIONS (not PII on their own) ===
    "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO",
    "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI",
    "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO",

    # === LEGAL / DOCUMENT TERMS ===
    "Registro Geral",
    "Cadastro Nacional",
    "Carteira Nacional",
    "Carteira De Trabalho",
    "Titulo De Eleitor",
    "Título De Eleitor",
    "Certidao De Nascimento",
    "Certidão De Nascimento",
    "Certidao De Casamento",
    "Certidão De Casamento",
    "Boletim De Ocorrencia",
    "Boletim De Ocorrência",
    "Procuracao",
    "Procuração",
    "Contrato Social",
    "Estatuto Social",
    "Termo De Compromisso",
    "Termo De Consentimento",
    "Declaracao",
    "Declaração",
    "Comprovante De Residencia",
    "Comprovante De Residência",

    # === COMMON SECTION HEADERS / FORM FIELDS ===
    "Nome Completo",
    "Data De Nascimento",
    "Estado Civil",
    "Endereco",
    "Endereço",
    "Telefone",
    "Celular",
    "Profissao",
    "Profissão",
    "Nacionalidade",
    "Naturalidade",
    "Filiacao",
    "Filiação",
    "Nome Da Mae",
    "Nome Da Mãe",
    "Nome Do Pai",
    "Sexo",
    "Genero",
    "Gênero",
    "Observacoes",
    "Observações",

    # === COMMON ROLES / TITLES (not PII) ===
    "Presidente",
    "Diretor",
    "Gerente",
    "Coordenador",
    "Supervisor",
    "Analista",
    "Consultor",
    "Assessor",
    "Secretario",
    "Secretária",
    "Tesoureiro",
    "Contador",
    "Advogado",
    "Procurador",
    "Delegado",
    "Juiz",
    "Desembargador",
    "Ministro",
    "Senador",
    "Deputado",
    "Vereador",
    "Prefeito",
    "Governador",
}

# Lowercase version for case-insensitive matching
PII_WHITELIST_LOWER = {term.lower() for term in PII_WHITELIST}


def is_whitelisted_term(text: str) -> bool:
    """Check if text is a whitelisted term (case-insensitive)."""
    return text.strip().lower() in PII_WHITELIST_LOWER


def is_whitelisted_term_exact(text: str) -> bool:
    """Check if text is a whitelisted term (exact case match)."""
    return text.strip() in PII_WHITELIST
